# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lkohn <lkohn@student.42.fr>                +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/03/03 13:13:02 by lkohn             #+#    #+#              #
#    Updated: 2025/03/03 13:30:46 by lkohn            ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Files
SERVER	=	server/server.c

CLIENT	=	client/client.c

LIBFT	=	cd libft && make

LIB		=	libft/libft.a

# Sources and Objects
